/* tslint:disable:no-any */
/* tslint:disable:no-namespace */
/** Declaration file generated by dts-gen */

export const bodyBlacklist: any[];

export const bodyWhitelist: any[];

export const ignoredRoutes: any[];

export const requestWhitelist: string[];

export const responseWhitelist: string[];

export function defaultRequestFilter(req: any, propName: any): any;

export function defaultResponseFilter(res: any, propName: any): any;

export function defaultSkip(): any;

export function errorLogger(options: any): any;

export function logger(options: any): any;

export namespace defaultRequestFilter {
    const prototype: {
    };

}

export namespace defaultResponseFilter {
    const prototype: {
    };

}

export namespace defaultSkip {
    const prototype: {
    };

}

export namespace errorLogger {
    const prototype: {
    };

}

export namespace logger {
    const prototype: {
    };

}

